export const GET_USER_DATA_REQUEST= 'GET_USER_DATA_REQUEST'
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS'
export const GET_USER_DATA_FAILURE='GET_USER_DATA_FAILURE'

export const REGISTER_USER_DATA_REQUEST= 'REGISTER_USER_DATA_REQUEST'
export const REGISTER_USER_DATA_SUCCESS = 'REGISTER_USER_DATA_SUCCESS'
export const REGISTER_USER_DATA_FAILURE='REGISTER_USER_DATA_FAILURE'

export const GET_USER_PRODUCT_REQUEST='GET_USER_PRODUCT_REQUEST'
export const GET_USER_PRODUCT_SUCCESS='GET_USER_PRODUCT_SUCCESS'
export const GET_USER_PRODUCT_FAILURE='GET_USER_PRODUCT_FAILURE'

export const ADD_CART_DATA_REQUEST='ADD_CART_DATA_REQUEST'
export const ADD_CART_DATA_SUCCESS='ADD_CART_DATA_SUCCESS'
export const ADD_CART_DATA_FAILURE='ADD_CART_DATA_FAILURE'

export const GET_CART_DATA_REQUEST='GET_CART_DATA_REQUEST'
export const GET_CART_DATA_SUCCESS='GET_CART_DATA_SUCCESS'
export const GET_CART_DATA_FAILURE='GET_CART_DATA_FAILURE'

export const DELETE_CART_DATA_REQUEST='DELETE_CART_DATA_REQUEST'
export const DELETE_CART_DATA_SUCCESS='DELETE_CART_DATA_SUCCESS'
export const DELETE_CART_DATA_FAILURE='DELETE_CART_DATA_FAILURE'

export const GET_REG_DATA_REQUEST='GET_REG_DATA_REQUEST'
export const GET_REG_DATA_SUCCESS='GET_REG_DATA_SUCCESS'
export const GET_REG_DATA_FAILURE='GET_REG_DATA_FAILURE'
